services:
  - type: web
    name: my-mern-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
